version: '3'
services:
    # ===============================front============================================
  front:
    container_name: front
    image: "54.223.52.77:5000/topdmc/cpp_front:1.0.0"
    networks:
      - web
    volumes:
     - /Users/datadir/nginx/logs:/var/logs/nginx/
    links:
      - "api:api"
    ports:
     - "80:80"
    restart: always
    # =================================api==========================================
  api:
    container_name: api
    image: "54.223.52.77:5000/topdmc/cpp_api:1.0.0"
    networks:
      - web
    links:
      - "elasticsearch:elasticsearch"
      - "mysql:mysql"
    environment:
      - RAILS_ENV=production
      - ELASTICSEARCH_SERVER=elasticsearch:9200
      - DATABASE_URL=mysql2://root:topdmc/cpp_tool
    ports:
      - "3000:3000"
    restart: always
  # ================================elasticsearch===========================================
  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:5.2.2"
    ports:
      - "9200:9200"
    networks:
      - web
    volumes:
      - /Users/datadir/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    # ==============================mysql=============================================
  mysql:
    container_name: mysql
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=topdmc
    volumes:
      - /Users/datadir/db:/var/lib/mysql
    build:
      context: .
      args:
        - character-set-server=utf8mb4
        - collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always
    # ===========================================================================

networks:
  web:
    driver: bridge
